//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        public string product_id { get; set; }
        public string product_name { get; set; }
        public string product_description { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> selling_price { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
